import { RotateCcw, X } from 'lucide-react'
import type { CollectionFilters, CollectionSummary } from '../types'

export const emptyCollectionFilters: CollectionFilters = { theme: '', condition: '', gift: '', purchaseDateFrom: '', purchaseDateTo: '', priceMin: '', priceMax: '', partsMin: '', partsMax: '', sort: 'newest' }

type Props = { filters: CollectionFilters; summary: CollectionSummary; onChange: (filters: CollectionFilters) => void; onClose: () => void }

export function CollectionFiltersPanel({ filters, summary, onChange, onClose }: Props) {
  const update = (key: keyof CollectionFilters, value: string) => onChange({ ...filters, [key]: value } as CollectionFilters)
  return <div className="filters-panel"><div className="filters-head"><div><strong>Filtrer et trier</strong><span>Affinez toute votre collection</span></div><button onClick={onClose} aria-label="Fermer les filtres"><X /></button></div><div className="filters-grid"><label>Tri<select value={filters.sort} onChange={(event) => update('sort', event.target.value)}><option value="newest">Ajout récent</option><option value="oldest">Ajout ancien</option><option value="purchase_date_desc">Achat récent</option><option value="purchase_date_asc">Achat ancien</option><option value="price_desc">Prix décroissant</option><option value="price_asc">Prix croissant</option><option value="parts_desc">Plus de pièces</option><option value="parts_asc">Moins de pièces</option></select></label><label>Thème<select value={filters.theme} onChange={(event) => update('theme', event.target.value)}><option value="">Tous les thèmes</option>{summary.themes.map((item) => <option key={item.label}>{item.label}</option>)}</select></label><label>État<select value={filters.condition} onChange={(event) => update('condition', event.target.value)}><option value="">Tous les états</option>{summary.conditions.map((item) => <option key={item.label}>{item.label}</option>)}</select></label><label>Cadeau<select value={filters.gift} onChange={(event) => update('gift', event.target.value)}><option value="">Tous</option><option value="true">Cadeaux uniquement</option><option value="false">Achats uniquement</option></select></label><label>Date d’achat — du<input type="date" value={filters.purchaseDateFrom} onChange={(event) => update('purchaseDateFrom', event.target.value)} /></label><label>Au<input type="date" value={filters.purchaseDateTo} onChange={(event) => update('purchaseDateTo', event.target.value)} /></label><label>Prix minimum (€)<input type="number" min="0" step="0.01" value={filters.priceMin} onChange={(event) => update('priceMin', event.target.value)} /></label><label>Prix maximum (€)<input type="number" min="0" step="0.01" value={filters.priceMax} onChange={(event) => update('priceMax', event.target.value)} /></label><label>Pièces minimum<input type="number" min="0" step="1" value={filters.partsMin} onChange={(event) => update('partsMin', event.target.value)} /></label><label>Pièces maximum<input type="number" min="0" step="1" value={filters.partsMax} onChange={(event) => update('partsMax', event.target.value)} /></label></div><button className="filters-reset" onClick={() => onChange(emptyCollectionFilters)}><RotateCcw /> Réinitialiser les filtres</button></div>
}
